name: Build and deploy

inputs:
  aws-access-key-id:
    description: AWS access key ID
    type: string
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    type: string
    required: true
  aws-region:
    description: AWS region
    type: string
    required: true
  backend-config:
    description: Terraform backend configuration (e.g. backend.hcl)
    type: string
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
        uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      run: |
        if [ -n "${{ inputs.backend-config }}" ]; then
          terraform -chdir=infrastructure init -backend-config=${{ inputs.backend-config }}
        else
          terraform -chdir=infrastructure init
        fi

    - name: Validate Terraform
      run: terraform -chdir=infrastructure validate

    - name: Plan Terraform
      run: terraform -chdir=infrastructure plan

    - name: Apply Terraform
      run: terraform -chdir=infrastructure apply -auto-approve

